"""add loan business context fields

Revision ID: 454be984e4ac
Revises: 1a1d45cda6e7
Create Date: 2026-05-08 14:59:38.599370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454be984e4ac'
down_revision: Union[str, Sequence[str], None] = '1a1d45cda6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('loan_applications', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('loan_applications', sa.Column('purpose_details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'purpose_details')
    op.drop_column('loan_applications', 'employment_type')
    op.drop_column('loan_applications', 'monthly_salary')
    # ### end Alembic commands ###
